spring:
  # Batch job config
  batch:
    job:
      enabled: false

# Log level config
logging:
  level:
    com.alklid.batch: DEBUG
  file:
    path: ./logs
    name: ./logs/snapshot-labeling

# snapshot config
snapshot:
  source: /Users/chris/Snapshot/tmp/source
  target: /Users/chris/Snapshot/tmp/target
