spring:
  # Batch job config
  batch:
    job:
      enabled: false

# Log level config
logging:
  level:
    com.alklid.batch: DEBUG
  file:
    path: ./logs
    name: ./logs/snapshot-labeling

# Sentry
sentry:
  dsn: ${SENTRY_DSN}
  release: ${BUILD_VERSION}
  environment: ${CONFIG_NAME}
  enable-tracing: true
  send-default-pii: false # 사용자 정보 기록
  logging: # 범위
    minimum-event-level: "WARN"
    minimum-breadcrumb-level: "INFO"
  sample-rate: 1